### ISSUE TITLE
Crash while browsing through the items

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [grim3212/grim-pack#1]
I believe this crash is for you. I was browsing the items added and noticed grim in the stacktrace

http://pastebin.com/Kv0xene8

**Comment by awkwaRdcaRRot** [comment]
Just tested again and it seems to be happening on the 3rd page of JEI, I'm guessing one of the items after the walls.

**Comment by JosEffigy** [comment]
similar problem. crashed when opening part of the book.
http://pastebin.com/irKzfUyB

**Comment by grim3212** [comment]
@awkwaRdcaRRot Yeah seems to something with the new way coloring works. I'll take a look at this tomorrow.

@JosEffigy This seems to be a different issue.

**Comment by medsal15** [comment]
It happened to me while I was browsing through the decor tab.

**Comment by grim3212** [comment]
Were you guys using a modpack because I am unable to recreate this and I don't really want to download each mod manually.

**Comment by awkwaRdcaRRot** [comment]
I was using a custom modpack that I made. I can try adding your mod to like the all mod pack when I get home and see if I get the same error. There is  a lot of crossover with mine and that one.

**Comment by grim3212** [comment]
Okay actually I just downloaded that I tried it out. Gave me the same error so you don't need to do that.
