### ISSUE TITLE
Using Neptune Staff to Freeze Mobs crashes game

### ISSUE THREAD

**Issue by mahilo3550** [grim3212/grim-pack#102]
###### Forge Version: 1.12.2-14.23.0.2512
------
I have "Tool Key 1" set to 'X' and when I hold 'X' and right click a mob with the Neptune Staff (have not tried with Phoenix Staff) my game crashed and won't let me start it back up until I go in and remove the "frozen" entity in MCEdit.

**Comment by grim3212** [comment]
Did it give you any error report?

I am unable to reproduce this so I'll need more information. 

On Server, Lan, SinglePlayer, maybe a mod list?

**Comment by mkozuma** [comment]
I am having the same issue. When I try to freeze a mob, my minecraft crashes with the following error message, "The game crashed whilst rendering entity in world
Error: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: layerRenderers." I am doing this in a singleplay superflat world using the following other mods: Advanced Swords, Biomes o Plenty (not in a BOP world though), Voidcraft, Just Enough Items, More Commands, OptiFine HD, and Tam Modized.

**Comment by grim3212** [comment]
Yeah I figured out what it was. A fix will be out either today or tomorrow.
