### ISSUE TITLE
Client crash/Obsidian recipe

### ISSUE THREAD

**Issue by jusjudge** [grim3212/grim-pack#105]
###### Forge Version: 14.23.0.2542
------
I was sent here by a contributor from JEI's github on an issue I am having with obsidian. They helped me to come to realize that there is actually something within your mod that causes my minecraft client to crash whenever I try to check JEI on ways to make obsidian.

**Comment by grim3212** [comment]
Okay I'll look into it.
https://github.com/mezz/JustEnoughItems/issues/1042

**Comment by grim3212** [comment]
Are you doing anything special to make this happen?

I am not able to reproduce the crash. I do see that somehow the milk bucket which can only hold milk is somehow holding water which is never supposed to happen but I can't get it to do that. Are you using a modpack or do you know of any other mods that you are using that might modify it?

**Comment by jusjudge** [comment]
I am using about 200 mods in a private modpack. 

To be exact about the situation though, I try to look at ways to make obsidian in JEI. When I click on the key bind I have to show the recipes and I scroll through them, it might let me scroll through it's recipes a bit but when I get to a certain recipe, my client freezes and then crashes. I've gotten this crash several times before and I have yet to understand exactly what's causing it.

**Comment by grim3212** [comment]
Okay, well I am guessing another mod is modifying the Fluid inside. Do you know if it's a certain machine page that it always crashes on or anything like that. Maybe I can find the mod that is contributing to the problem and fix it on my end.

**Comment by jusjudge** [comment]
I'm currently at work but as soon as I get home I will update you on that. I want to say from the top of my head though that the crash occurs before I go on a specific recipe for obsidian before it crashes.

**Comment by grim3212** [comment]
Okay sounds good

**Comment by jusjudge** [comment]
@grim3212 So, I just tried testing it out and it crashes whenever I press the crafting tabs to switch to different mods that allow me to craft it.
I just launched it back up and immediately pressed on obsidian to show it's crafting recipes and it let me scroll through all the options then crashed and that's the report I got.

https://pastebin.com/ZafdiL7U

**Comment by grim3212** [comment]
Okay if possible could you test it out without GrimPack installed and tell me what categories of pages there are for Obsidian that way I can try to find the other mod that it might be conflicting with.

EDIT: Never mind I was able to get it to cash on my end. I'll try and figure out whats wrong.

EDIT EDIT: Found out is a conflict with Industrial Craft and their obsidian recipe. I think I am not restricting what can fill the milk bucket.
