### ISSUE TITLE
[request] Alter the cheese maker block to not cull textures of adjacent blocks

### ISSUE THREAD

**Issue by stohun01** [grim3212/grim-pack#107]
###### Forge Version: 14.23.0.2545
------
I'm working on resources for a mod pack and I want to have the cheese maker look like the other barrels (the end two are the storage barrel and brewing barrel from Rustic). Could you please change the block so it doesn't cull its neighbors?
![2017-11-30_15 59 33](https://user-images.githubusercontent.com/23627406/33416667-8e198d9a-d5e9-11e7-8b04-0cc1dcea9123.png)

**Comment by grim3212** [comment]
I had no idea it did this. I'll try and get to it later today.

**Comment by stohun01** [comment]
Also, I noticed the textures on the cheese block model are stretched. This should fix it:
```
{
	"textures": {
        "particle": "grimpack:blocks/cheese_block",
        "all": "grimpack:blocks/cheese_block"
    },
	"elements": [ 
		{
	    "from": [  1, 0,  1 ],
	    "to":   [ 15, 8, 15 ],
	    "faces": {
			"down":  { "uv": [ 1, 1, 15, 15 ], "texture": "#all", "cullface": "down" },
			"up":    { "uv": [ 1, 1, 15, 15 ], "texture": "#all" },
			"north": { "uv": [ 1, 8, 15, 16 ], "texture": "#all" },
			"south": { "uv": [ 1, 8, 15, 16 ], "texture": "#all" },
			"west":  { "uv": [ 1, 8, 15, 16 ], "texture": "#all" },
			"east":  { "uv": [ 1, 8, 15, 16 ], "texture": "#all" }
			}
		}
	]
}
```

**Comment by grim3212** [comment]
Okay so I think that for the cullface that that shouldn't be handled on my end since by default it should be culled. So, instead I just added a cheese_maker model so that you can adjust the cullfaces how you like, although I am pretty sure with was possible before hand anyway. It's just more convenient now.

If you think that works then I'll go ahead and release an update with this.

**Comment by stohun01** [comment]
Culling faces in a block model affects only itself when it's next to a solid block. I was requesting that the cheese maker block be altered so as to not be considered solid. But rather opaque or transparent (not sure of the correct term) similar to a fence or enchanting table type of block. I could just as easily make my barrel model a bit thicker to occupy the whole block, it's just a small cosmetic thing.

**Comment by grim3212** [comment]
Oh I guess I thought culling faces worked slightly different. I can should be able to do that then.
