### ISSUE TITLE
[1.12.2, SpongeForge] Attractor, Repulsor and Gravitor crash (and their directional versions)

### ISSUE THREAD

**Issue by polyzium** [grim3212/grim-pack#108]
###### Forge Version: 14.23.1.2560
------
Playing on a SpongeForge server. When i turn on any of these blocks, the server crashes. Crash log: https://clbin.com/TYj1K

Running SpongeForge version 2555-7.0.0-BETA-2758.

**Comment by grim3212** [comment]
Okay just tested and this happens with Forge and SpongeForge. I'll try and get this fixed when I have time today or tomorrow.

**Comment by polyzium** [comment]
Alright i am waiting for the fixed build on curseforge
