### ISSUE TITLE
Chicken Suit effects are "sticky"

### ISSUE THREAD

**Issue by Darkmega18** [grim3212/grim-pack#109]
###### Forge Version: 1.12.2 - 14.23.1.2562
------
The speed 4 gotten from the full chicken suit sticks because it permanently stays at zero secs but active once you take off a piece of the suit. The floating effect is also sticky until you remove every piece. but I'm not sure if thats intentional or not. Unless the floating part doesn't require all pieces?
The jumps definitely work as intended tho,

**Comment by grim3212** [comment]
The floating effect is intended but the speed 4 shouldn't be coming from the chicken suit. The only thing the chicken suit should give you is the extra jumps and glide effect.

Some other mod must be causing the speed 4 effect.

**Comment by Darkmega18** [comment]
I swear I sent a second message last night. I must've typed it and forgot to hit comment. but the chicken pet I had was causing it. and it goes away when it's not on my hotbar. so I found out what was doing it. since I had a quest that gave a chicken suit and a chicken pet all at once.

**Comment by grim3212** [comment]
Oh okay that makes sense. Good luck
