### ISSUE TITLE
Grim Pack Client Crash

### ISSUE THREAD

**Issue by jusjudge** [grim3212/grim-pack#113]
###### Forge Version: 14.23.1.2570
------
I updated the mod from 5.2.11.68 which works perfectly fine, to the latest version and when I load up my game I am able to walk around for a bit and then my client freezes. It either freezes and then crashes or I might have to manually force close the client. Either way when it happens I get this [crash.](https://hastebin.com/biwaforeni.sql) Hopefully that helps.

**Comment by grim3212** [comment]
Is it just grim pack that you updated? It looks like chisel has a hand in that crash and I don't see a mention of grim pack.

**Comment by grim3212** [comment]
No response and didn't look like it was the fault of GrimPack.
