### ISSUE TITLE
weird exception when trying to join server(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [grim3212/grim-pack#114]
###### Forge Version: 1.12.2-2582
------
exception:
https://pastebin.com/0acu4WKy

**Comment by grim3212** [comment]
I am pretty sure that this isn't a problem with GrimPack and is a problem with DummyCore. I recommend reporting it to them here https://github.com/Modbder/DummyCore/issues

**Comment by SDUBZ** [comment]
it is after going through it finely also noticed its to do with essential craft aswell
can you plz leave this open to reference back to
i will close once all the issues are dealt with :)

**Comment by SDUBZ** [comment]
@grim3212 can i ask why this might be happening?
[12:50:18] [main/INFO] [grimpack/]: {Grim Pack}: Syncing config from server...
[12:50:18] [main/INFO] [grimpack/]: {Grim Pack}: Updating manual pages...
[12:50:18] [main/DEBUG] [FML/]: Reverting to frozen data state.

client latest if helps http://puu.sh/yT53D/28776ca2e0.log

**Comment by grim3212** [comment]
That is how it syncs the server configs with the clients. And then it updates the manual pages accordingly with what config values are set.
