### ISSUE TITLE
Question-how to enable buckets holding partial bucket amounts?

### ISSUE THREAD

**Issue by PurpleHel** [grim3212/grim-pack#115]
###### Forge Version: 14.23.1.2560
------
Buckets used to hold partial amounts, like 800mb or whatever. They don't anymore. Is there a setting in the config that I'm missing to enable this? It was really useful, for adding lava to my TConstruct smeltery, and moving canola oil around in Actually Additions stuff.

**Comment by grim3212** [comment]
I changed it because then the buckets wouldn't be able to place the fluids in the world anymore so you would just be stuck with it until you empty or fill it.

I guess I could add that as a config option.

**Comment by PurpleHel** [comment]
A config option would be awesome! I hadn't even noticed you couldn't place fluids in the world, since it integrated so well with the containers from various mods. :)

**Comment by grim3212** [comment]
Okay the new version is now uploading with the config allowPartialBucketAmounts to true it should act as before.

**Comment by PurpleHel** [comment]
Sweet! Thanks!
