### ISSUE TITLE
Slingshots do not work server

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [grim3212/grim-pack#117]
###### Forge Version: spongeforge-1.11.2-2476-6.1.0-BETA-2792
------
Slingshots do not work.
When a shot is fired by any type of projectile, the client is stained. The server continues to work as usual.
Please adapt for the server.
Crash-report, unfortunately, no. It simply is not created.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained. For future Slingshots look towards Assorted Mods.
