### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by 0dikpah** [grim3212/grim-pack#119]
###### Forge Version: 14.23.4.2759
[crash-2018-09-01_08.52.27-client.txt](https://github.com/grim3212/grim-pack/files/2342131/crash-2018-09-01_08.52.27-client.txt)

------

**Comment by grim3212** [comment]
Oops. Seems when I changed JER I forgot to still make it work without it. I'll fix when I'm back on Monday

**Comment by 0dikpah** [comment]
okay thank you:)
