### ISSUE TITLE
[Suggestion] Multitools function

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#12]
It came to my attention(via Waila and mining speed) that the Multitools are somewhat not correctly registered as Pickaxe, Axe, and Shovel.
It is apparent as some block, mainly modded or "non-natural" one, are mined fairly slow.
Waila also sometime say that they are not high level enough to mine the block(even though sometime they do)

Also, a good thing would be for them not to lose durability when use to break grass-type or leaves block, as of now they lose durability pretty fast(which I think should not be the case for instant breaking block like tall grass at least)

You opinion? ;)

**Comment by drakray** [comment]
Also, Multitools should show their durability under "When in main hand" when Advanced Tooltips(F3+H) is on

**Comment by grim3212** [comment]
Also, I can see durability when advanced tooltips are on so I don't know why you wouldn't.

**Comment by drakray** [comment]
Forget about that, i just saw that Durability only shows when at least 1 damage is taken lol(that's what happen when you go too fast in debugging and don't multicheck your stuff XD )

**Comment by grim3212** [comment]
Haha yeah. I've done that before.
