### ISSUE TITLE
Crash upon searching the item fence, possible incompatibility with Betweenlands

### ISSUE THREAD

**Issue by BugmanBugman** [grim3212/grim-pack#122]
###### Forge Version: 
------
https://paste.dimdev.org/meliwibaxo.mccrash

**Comment by grim3212** [comment]
Looks like this has been fixed with the latest update for The-BetweenLands.

https://github.com/Angry-Pixel/The-Betweenlands/issues/749

@GoryMoon
If something should change on my end let me know.
