### ISSUE TITLE
Slingshot Pellets Do No Damage to Target

### ISSUE THREAD

**Issue by ScottoMotto** [grim3212/grim-pack#123]
###### Forge Version: 2772
------
Slingshot Pellets do literally 0 damage to target. It has something to do with the conversion from double to float as the values come in from the config. 
Playing with the code in a dev environment if I hardcode values in EnumPelletType.java then it works as expected. Probably an easy fix but it is eluding me after ~1hour testing.

(this is scottosx btw if you remember. I did some initial work with these slingshots and ore fungus)

**Comment by grim3212** [comment]
Interesting I'll take a look tonight. Nice to see you again.

**Comment by grim3212** [comment]
Enums are pretty much constant without some modifications so it was being created before the config was read. c0c115f Closes this.
