### ISSUE TITLE
[Request] Fungus Blocks should Inherit from Slime Blocks

### ISSUE THREAD

**Issue by ScottoMotto** [grim3212/grim-pack#125]
With bounciness, fall damage reduction, sounds, etc.

**Comment by grim3212** [comment]
Possibly I'm not sure if fungus is the same class as slime. If anything it might work like slime but heavily minified bounce, fall damage, etc... What do you think?

I'm not even sure how people use fungus. So I don't even know of this would be useful.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
