### ISSUE TITLE
[Request] Masks Should Have Effects

### ISSUE THREAD

**Issue by ScottoMotto** [grim3212/grim-pack#126]
Wearing a mask from a hostile mob should cause that mob to deagrro against the player. Masks from animals should act as temptations to cause the mob to follow the player.

Recipe balance might need adjustment with this greater power.

**Comment by grim3212** [comment]
That definitely would be cool and something I have always wanted to implement but I don't really have the time for big changes anymore. Maybe in the future but as of right now I don't see this happening anytime soon.

Also we are still missing some mob masks so I'd probably implement those first.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
