### ISSUE TITLE
[suggestion] A theme about throwable thing 

### ISSUE THREAD

**Issue by MokoBlack** [grim3212/grim-pack#127]
Just make  funny :-）
can u add some item that can be throwing?
  example ：
                    **Cleaver** [ hitting the target will cause it to bleed (team fortress 2 ? XD) ]
                    **Hatchet** [more range damage]
                    **Sandwich snowball** [stuff something into the snowball will get different effect for that]
                     **Watermelon** [just the vanilla one in the field ,player can use shift+right to click lift it up and throw it ]
                    **Bottled magma** [throw on hit to generate flow lava(it will disappear soon) ]
                    **Record** [just the vanilla too, powerful dart because it's hard to get a simple way to get records,also different record have special effect (throw into the jukebox can also play it , cool)]
                    **Book** [( Knowledge is power!! )Get different throwing effects by enchanting. ]
                     **Skull** [maybe a little tracking effect?]
                     **Playing cards** [a set of playing cards , the throwing weapon based on luck, the Joker is the best attack of them]
                    **Detonation pickaxe**[Mmmm ..just funny and funny]

**Comment by grim3212** [comment]
This seems interesting ideas some of them are definitely cool. Right now I don't have the time to implement these but I might be able to in the future but no promises.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
