### ISSUE TITLE
[Bug] Chicken Suit not working without HammerCore

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#128]
###### Forge Version: 2775
------
Self-explanatory title, if I remove HammerCore from my pack, Chicken Suit no longer work.
I can post a modList/log if it can help, or is it a dependency now?

**Comment by drakray** [comment]
It FeatherFalls, but I can't MultiJump

**Comment by drakray** [comment]
Well, I found why: conflict with Space as Ascend for Viescraft.
Seems like if key_key.jump is not set to something unique, ChickenSuit don't jump, even if the key is set for something specific like OnVehicle and such.
Will have to set Ascend to something else.

**Comment by grim3212** [comment]
@drakray Interesting. If it proves to be something that I need to change on my end let me know.

**Comment by drakray** [comment]
should maybe test with conflicting key with other mods(where the jump is use for other thing)
now that I think about it though, the Chicken Jump Sound play even in creative and when seated in ViesCraft Balloon, I'll test with Boat and Minecart, but I think this might be symptom of underlying potential problem
