### ISSUE TITLE
[Suggestion] Chicken Enchantment

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#132]
Self-explanatory: an enchantment that could give the Chicken Suit Jumping Effect on any armor piece. Enchantment could be craftable by applying(second anvil slot) the Chicken Piece to the Armor(first anvil slot)

Might have a config too, just in case some find it OP

Is it a good one(suggestion)?

**Comment by grim3212** [comment]
This was added to the Assorted Mods variant.
