### ISSUE TITLE
Infinite obsidian 

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [grim3212/grim-pack#135]
###### Forge Version: 2768

The video shows the process itself
https://i.gyazo.com/622342bbcf002c2d67d1f92112561901.mp4

**Comment by grim3212** [comment]
This isn't really an issue in my eyes as that is how vanilla Minecraft works when mixing fluids.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
