### ISSUE TITLE
Crash with Dude Where's My Horse mod upon startup

### ISSUE THREAD

**Issue by BugmanBugman** [grim3212/grim-pack#136]
###### Forge Version: 1.12.2 - 14.23.5.2823
------
https://paste.dimdev.org/yejumuxehu.mccrash

**Comment by grim3212** [comment]
It looks like it doesn't like Ice Pixie's. I'm not sure when I'll get to this because my main focus is 1.13 with the little time I have. But next time I touch 1.12 I'll take a look.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
