### ISSUE TITLE
Functional offer

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [grim3212/grim-pack#137]
Is it possible to make a hot key for auto-install torches?

**Comment by grim3212** [comment]
What do you mean by auto-install torches?

**Comment by xxxLEOPARDxxx** [comment]
Hello!
First of all, thanks for your wonderful mod!

I mean do one of two things:
1. Is it possible to make a hot key for the on / off auto-setting option for torches, so as not to go into the mod settings?
https://i.gyazo.com/6bda50181e5a9a43f8014b59443270e7.png
2. Is it possible to install torches on a hot key, as it is implemented in MinersAdvantage? This function was there very, very useful, but unfortunately, the author apparently abandoned the mod.

Thank you in advance!

**Comment by grim3212** [comment]
So definitely could make it so that it can be toggle via hotkey.
As for the second part I still don't think I know what you mean.

What does install torches on a hot key mean?

**Comment by xxxLEOPARDxxx** [comment]
I apologize for Google translator ...
On the second point ...
Just so that by pressing the key, a torch was taken from the inventory and installed on the unit, which is in sight.
Suppose we press the combination of keys SHIFT + V and the torch is mounted on the block that is in sight.

**Comment by grim3212** [comment]
Okay I see what you are saying. That is a possibility the 1st one is a lot more likely for me to implement.

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
