### ISSUE TITLE
Grim Pack crashes on startup with Stellar Sky and Just Enough Resources

### ISSUE THREAD

**Issue by Dimentive** [grim3212/grim-pack#140]
Crash report: https://pastebin.com/raw/THL35tKG

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2824 (latest)
* **[Grim Pack](https://minecraft.curseforge.com/projects/grim-pack):** [6.0.0.6](https://minecraft.curseforge.com/projects/grim-pack/files/2637926) (latest)
* **[Stellar Sky](https://minecraft.curseforge.com/projects/stellar-sky):** [0.5.3.2](https://minecraft.curseforge.com/projects/stellar-sky/files/2580020) (latest)
* **[Stellar API](https://minecraft.curseforge.com/projects/stellar-api):** [0.4.2.9](https://minecraft.curseforge.com/projects/stellar-api/files/2568537) (latest release version)
* **[Just Enough Items](https://minecraft.curseforge.com/projects/jei):** [4.15.0.273](https://minecraft.curseforge.com/projects/jei/files/2694170) (latest)
* **[Just Enough Resources](https://minecraft.curseforge.com/projects/just-enough-resources-jer):** [0.8.9.48](https://minecraft.curseforge.com/projects/just-enough-resources-jer/files/2599965) (latest beta version)

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
