### ISSUE TITLE
[Suggestion] Spawn Dimension setting

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#142]
###### Forge Version: 2847
------
A config to set where mobs can spawn, because right now, there is Treasure mobs in every dimension, specifically in the 50-51-52-53, dimension from Abyssalcraft

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained. P.S. I never like Treasure Mobs 😅

**Comment by drakray** [comment]
yeah that's old stuff XD
(I honestly don't even remember this lol)
