### ISSUE TITLE
Issue with functionality when enabled with Wearable backpack mod

### ISSUE THREAD

**Issue by Darkmega18** [grim3212/grim-pack#143]
###### Forge Version:  14.23.5.2855
------

Grim, would you have any idea why the mod seems to disable the ability to use the Wearable backpack mod's B button and rightclick functions to open and place down the backpacks? not sure if specifically the wearable backpacks mod, but it's atleast an issue with the special version within the super hostile modpack by Vechs linked here:

https://www.curseforge.com/minecraft/mc-mods/finarris-wearablebackpack-toughasnails-fix

my config has most of the extra stuff in grimpack disabled other than the healing, food items, some of the world gen for food and decorative items like the copy blocks etc.

Just having it installed stopped me from interacting with the backpack other than shift breaking it to put it on. but once I had it on the B button or any other button wouldn't allow me to open it, nor could I place it backdown, there didn't seem to be any bugs happening although I forgot to look at console. Once I disabled grimpack the functionality returned just fine. so not sure whats happening.

**Comment by grim3212** [comment]
It's been quite a while since I looked at grimpack. But, at least from the sounds of what you have enabled I am not sure why it would stop it. If you end up getting a console log that may point to something that could help. But, I don't really support it anymore.

**Comment by Darkmega18** [comment]
well darn, alrighty. if I attempt to revisit it for the light sources etc I'll keep an eye out. Would you have applied any keybinds in that general area that could disrupt it?

**Comment by grim3212** [comment]
It shouldn't. All the keybinds setup only should trigger if you are holding a supported item in your hand besides FusRoDah. But at least from what it sounds like you have disabled I don't even think there are any keybinds setup at all. If you ever retry I would look at the console to see if it is throwing errors. But again it has been I think like 2 years since I updated it so maybe the later Forge versions of 1.12.2 broke something. 🤷‍♂️

**Comment by Darkmega18** [comment]
potentially. alright, I'll take a try again. I've still got the configs intact so it'd be just a case of looking for salty pop-ups in the logs or console.

**Comment by Darkmega18** [comment]
there doesn't seem to be anything popping up in console. :< it just breaks the moment the mod is installed.

**Comment by Darkmega18** [comment]
ok, so it just REALLY doesn't like that keybind (B) do you use B for any of your defaults which could be being registered but not appearing at all cause I've disabled the mods which would use them? cause I moved it from B to comma (nearest input I had which didn't conflict with anything else) and it started working fine again. U also works seemingly. and so probably literally anything else that doesn't already have a conflicting key bind should work I'd think... I've noticed there are some mods which really don't like having conflicting keybinds, either cause of how they're made or some other strangeness. it's happened with the hooked mod's grappling hooks also where they don't agree with using C unless everything else is the pack isn't using C. :V

_an edit later:_
gonna see about turning on all the features temporarily, disabling the keybinds if any turn up. then turning all the different parts back off again. >_>

_the next edit:_
somethingsomething auto-torch? when I B, auto-torch is toggled when I've got all things enabled. and there is literally no keybind for it in the list. so it seems the auto-torch keybind might be colliding with it, cause I actually tried the button for backpack on other inputs, and it turns out it does actually work even with conflicting, it's just this particular keybind you happen to have makes it break ultra hard. Any chance of that being looked at?

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained.
