### ISSUE TITLE
[QUESTION] Is not possible to speed up the refinery?

### ISSUE THREAD

**Issue by Klairm** [grim3212/grim-pack#144]
So I have seen that the refinery is quite slow, is there any way to increase the speed of it?

**Comment by Klairm** [comment]
Also, I noted that if you put a hopper in the bottom of the refinery it will output the item you're refining and not the refined item

**Comment by grim3212** [comment]
Unfortunately GrimPack is pretty out of date in a lot of things like that. Especially when it comes to trying to automate any of the machines. I also don't maintain this anymore instead focusing on the newer updates with the Assorted Mods.

**Comment by Klairm** [comment]
> Unfortunately GrimPack is pretty out of date in a lot of things like that. Especially when it comes to trying to automate any of the machines. I also don't maintain this anymore instead focusing on the newer updates with the Assorted Mods.

And what should I edit manually on the source to change the speed time? I honestly never use Java and I see a lot of files xD

**Comment by grim3212** [comment]
Ugh it's been quite a while but I think it's this. https://github.com/grim3212/grim-pack/blob/c6c824545497b2ac39749d8cb19062fc1493253d/src/main/java/com/grim3212/mc/pack/industry/tile/TileEntityMachine.java#L236 

Hopefully that's it.

**Comment by Klairm** [comment]
> Ugh it's been quite a while but I think it's this.
> 
> https://github.com/grim3212/grim-pack/blob/c6c824545497b2ac39749d8cb19062fc1493253d/src/main/java/com/grim3212/mc/pack/industry/tile/TileEntityMachine.java#L236
> 
> Hopefully that's it.

Thanks a lot will try this, now I'm just having problems trying to compile with gradle, I got an error saying that the forge plugin was not found, and I checked the build.gradle and I found out that "https://files.minecraftforge.net/maven" is no longer avaible, is that the problem? sorry for bother you in an outdated project but I would really want to compile this.

to be precise the error is 
```
Build file '/home/n/grim-pack/build.gradle' line: 27

A problem occurred evaluating root project 'grim-pack'.
> Failed to apply plugin 'net.minecraftforge.gradle.forge'.
   > Configuration with name 'compile' not found. 


```

**Comment by grim3212** [comment]
Definitely sounds like it not really sure what it needs to change to though sorry. I recommend checking out some active 1.12 mods sources to see what they use for the forge plugin

**Comment by Klairm** [comment]
> Definitely sounds like it not really sure what it needs to change to though sorry. I recommend checking out some active 1.12 mods sources to see what they use for the forge plugin

got that solved now, but I'm getting errors with some strange "§" characters that doesn't seem to be UTF-8 compatible, since I get `error: unmappable character for encoding UTF8`  from here https://github.com/grim3212/grim-pack/blob/master/src/main/java/com/grim3212/mc/pack/core/util/generator/GeneratorUtil.java  this is the last problem I have

**Comment by grim3212** [comment]
That's the character Minecraft uses for text changes like changing the color. The generator class is only used to create documentation so you should be able to comment out what is causing the issue.

**Comment by Klairm** [comment]
> That's the character Minecraft uses for text changes like changing the color. The generator class is only used to create documentation so you should be able to comment out what is causing the issue.

This code is being generating by something else that I'm not sure what is, so If I delete it it will be generated again when I compile

**Comment by Klairm** [comment]
> > That's the character Minecraft uses for text changes like changing the color. The generator class is only used to create documentation so you should be able to comment out what is causing the issue.
> 
> This code is being generating by something else that I'm not sure what is, so If I delete it it will be generated again when I compile

Think I just gonna leave this, every time I workaround something , 30 more errors come up haha, thanks for the time and patiencie anyway

**Comment by grim3212** [comment]
Okay, yeah I imagine it was a mess. No worries
