### ISSUE TITLE
Problem with cheese maker

### ISSUE THREAD

**Issue by Finleylp1** [grim3212/grim-pack#145]
###### Forge Version: 14.23.5.2855
------ When I use the Obsidian bucket for the last time (1000/32000) on the cheese maker
the bucket stays filled without emptying the bucket and doesnt show the bar.
![2021-11-07_12 12 01](https://user-images.githubusercontent.com/93863446/140642666-c6c05dae-25bf-4b68-86bd-f99028dd258d.png)

**Comment by grim3212** [comment]
Closing as GrimPack is no longer maintained. It looks like @JuniorWolfgamingDE is remaking Cuisine for newer versions.

https://github.com/JuniorWolfgamingDE/WMGAssortedCuisine
