### ISSUE TITLE
[Minor Bug] MultiTool mining level/speed

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#18]
Might be a TConstruct compatibility bug, but in Waila, the tool don't show a [correct minability](http://imgur.com/zLGaphd)
The block CAN be mined though.

Also, my Diamond MultiTool mine some stuff rather slowy, like the Vanilla Furnace

Inter-compatibility bug or overlook?

**Comment by drakray** [comment]
Also, MT now use 1 durability for breaking grass, and 2 for leaves. Intended?

**Comment by grim3212** [comment]
Seems that harvest levels were not being set properly.
