### ISSUE TITLE
Milk buckets render with black and purple texture, not white

### ISSUE THREAD

**Issue by Lothrazar** [grim3212/grim-pack#19]
Just some weird rendering with milk buckets.  Other liquids like lava, even from other mods like exp or the green essence, they render fine, its just milk

http://i.imgur.com/LCraJOK.png

**Comment by drakray** [comment]
Are you using the latest version? because this is supposed to be fix, and I don't see this in my modpack.
What is your mod list?

**Comment by grim3212** [comment]
Very strange. Right now mine is working looks like this. 
![2016-08-22_14 22 05](https://cloud.githubusercontent.com/assets/4063463/17872224/f4c406e0-6873-11e6-8f97-953c873a5329.png)

**Comment by drakray** [comment]
this issue as surfaced again with the .24 update
also, now using Usage on JEI don't work
![sans titre](https://cloud.githubusercontent.com/assets/4303126/18489514/d78bb906-79cb-11e6-99d7-5b2ce43c792a.png)

**Comment by grim3212** [comment]
Are you using any mods that have liquid milk? That might be the issue which I should be able to fix.

EDIT:
Also not sure what you meant about the JEI Usage

**Comment by drakray** [comment]
It was ok in .22, also, no liquid milk
![2016-09-13 17_12_40-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/4303126/18491669/763674e8-79d5-11e6-82fb-305b8498f362.png)

the JEI recipe viewer, (U)sage vs (R)ecipe
JEI list the Full bucket(Contains: X/X), but does not recognize them for recipe usage, as in, if I look up the Recipe for Dough, it show the GrimBucket Contains: 0/X

EDIT: problem does not exist with just JEI and GrimPack, i'm debuging to find the culprit

**Comment by drakray** [comment]
it's Reliquary (The fluid xreliquary:milk has been selected as the default fluid for milk)
the glitch exist only after I add Reliquary in my test instance

**Comment by grim3212** [comment]
Okay I thought it might end up being something like that. Let me see what I can do.
