### ISSUE TITLE
Crash w/ Veinmeiner

### ISSUE THREAD

**Issue by WenXin20** [grim3212/grim-pack#20]
My game crashed when I veinmined the random ore. 
Forge 2062
[Crash Report](http://pastebin.com/7w7eXH04)

**Comment by grim3212** [comment]
I am unable to recreate the crash. Was there anything special that you did to make this happen? I am unsure if this is a problem on my end.

**Comment by WenXin20** [comment]
The only other thing was that I was holding shift on a ladder while pressing a keybind (in my case "v") to use veinminer. In the config option of veinminer I changed it to use a keybind instead of pressing shift.

**Comment by grim3212** [comment]
I just tested that. I couldn't get it to crash. I think it might be another conflicting mod.

**Comment by WenXin20** [comment]
Ok
