### ISSUE TITLE
[Suggestion] Enchantability

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#22]
Since it is "Ultimate" shouldn't the Fist be enchantable?
I'd like to give it some looting/fortune, just to make it MORE overpowered :D

**Comment by grim3212** [comment]
Hahaha, I like the sound of that! I'll work on it

**Comment by drakray** [comment]
ETA on release?

**Comment by grim3212** [comment]
Out now! :smile:

**Comment by drakray** [comment]
Fancy, thanks :D
