### ISSUE TITLE
[Implemented Feature?] Ultimate fist durability

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#23]
Don't know if intended, but the Ultimate fist now have the durability of diamond came with enchantability

**Comment by grim3212** [comment]
Oops it was not intended but it lead to me making the Ultimate Fist more configurable.

**Comment by drakray** [comment]
good thing, there are never too much config :D

**Comment by drakray** [comment]
There seems to be a Bug™, "Ultimate Fist Can Be Damaged"=true is not working as of 
Forge 2314
MC 1.11.2
GP 4.0.1.17
