### ISSUE TITLE
[Suggestion] Flat Item Frame

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#26]
Self-explanatory, a king of Item frame that can be placed on horizontal surface, maybe over and under block, to allow for more decoration possibility
could be use to put stuff on table, without block specific code

**Comment by grim3212** [comment]
So, pretty much just an item frame that can be placed on any side of a block?

**Comment by drakray** [comment]
Could be, but since there is already Item Frame for vertical side, no need to make it, unless it is easier to just make "for all side".
Also, should not be required to be on a solid block like Torch, since some block are not "solid", but could always look good with some deco on them.
Maybe in fact a Frame for 6 faces, with no dependency on surface placed.
Don't know if i'm clear in what I mean lol XD ( english is not my first language :/ )

**Comment by grim3212** [comment]
Alright I just released the new update that includes this.

**Comment by drakray** [comment]
Seems to work nicely, once you get the hang of the rotating thingy lol
But I think it would be nice if, when using horizontal placed frame, 3d model could be placed "standing", as in top side up/down
Ex: placing a mob head on a floor frame, looking Sideway instead of Up
Possible?
Maybe in a config?

**Comment by grim3212** [comment]
Oops I guess the Milking Event for Better Buckets was screwing up the rotation for Flat Item Frames as well as vanilla frames.

**Comment by grim3212** [comment]
Changes have just been released.
https://minecraft.curseforge.com/projects/grim-pack/files/2328611

**Comment by drakray** [comment]
not found :/
maybe a Curse cooldown?

**Comment by grim3212** [comment]
Yeah it takes some time for the file to be accepted but it is up now.

**Comment by drakray** [comment]
oki
Could it be possible to have a config for custom item/block list that could be rotated like the block config, format
`mod:item:meta;mod:item:meta`?
also, to make it so that all Block behave like Head, as in slightly shifted to be seen entirely when horizontal?

**Comment by drakray** [comment]
allowing item to be added with a config could allow for some item with 3d model, like the Basic Element elemental Orb to be placed like block and look cool too XD

**Comment by grim3212** [comment]
Alright so I changed it to apply to all models that are in 3D so it should work for any items now too. And slight shifted the models out. 

If this works out I will release it.

https://drive.google.com/file/d/0B9vcVyJ8SwHMSFM5UzJrcl9NQ1E/view?usp=sharing

**Comment by drakray** [comment]
i'll try that live

**Comment by drakray** [comment]
it seems to work pretty well, but I haven't tried every block/item from all of my mods
I'll keep you posted if I found a crash/bug

**Comment by grim3212** [comment]
Alright

**Comment by drakray** [comment]
lil glitch, Creative Pick Block(default middle click) on Flat Frame gives Vanilla Item Frame(nothing serious)

**Comment by grim3212** [comment]
Okay that should be fixed. Anything else?

**Comment by drakray** [comment]
don't think so, I tried a lot of item/block from a couple of mods, and the only "glitch" I found was about some bad block model scaling, mainly from semi-broken mod, nothing on your side
I think it is stable enough, maybe we'll find some thing later, but given the nature of the Frame, all error should come from other mod with bad model habit

**Comment by grim3212** [comment]
Alright awesome! I'll put out a release sometime later today.
