### ISSUE TITLE
[Discussion] Connectivity between parts

### ISSUE THREAD

**Issue by grim3212** [grim3212/grim-pack#28]
So this is a place to give ideas on ways to have the parts be more connected with each other as well as connectivity with the blocks and items in each part too. 

If you have any ideas on ways t make the mod feel as it is more or less related.

Although if you like how it is now you can explain why.

I just needs some ideas on moving forward.

**Comment by scottosx** [comment]
I'm going to start throwing out some ideas for integrations that I have been thinking about. Think of this as brainstorming without all the details worked out. Here's the first.

Armory - a backpack implementation that allows you to store all of the various weapons and ammunition. Along with this a new 'multitool' like spring loader which cycles through the weapons in the armory from one hotbar slot. Maybe a key combination like control-right click if none of the weapons use that already. They are auto armed if the needed parts are in the bag.

So, with a few clicks you could have a slingshot, all the knives and tomahawk, the pokeball, spears, raygun, etc.. Choose your poison.

**Comment by scottosx** [comment]
Second idea:
Mixing the code from the gravity suction device and the pokeball make a 'entity vacuum' that pulls in all mobs within a radius, there could be a void version or a stored version. Radius could be determined by upgrades if you wanted to go that far for balance.
Imagine how cool it would be to clean out a whole area of a cave or spawner. You could also get all the animals needed for a farm or move an existing one in one pass.
This is the lines I am thinking along, how to mix functionality already included in the pack for massively more powerful tools. Tell me if I am on the right track.

**Comment by grim3212** [comment]
Yeah, I am liking these ideas. I just wanted something to make the different sections feel a little bit more connected instead of just being completely random. I have just went back to college so I am unsure how much time I'll have but these all sound really cool.

**Comment by scottosx** [comment]
I understand that modding is a hobby for most. I am trying to get into it myself having somewhat of a programming background but not yet up to speed with all of the MC stuff. Getting there quickly though. What I am saying is that I can help, a little at first up to my skill level but increasingly more if wanted. I can do textures and graphics as well.

So, I can get really specific if you wanted to break down some of these ideas into small manageable tasks. One of my major skills is 'hacking' around code to tailor it and learning that way. 

Some ideas have general applications but could have specific implementations in the pack. For instance, a sub inventory (backpack) whose contents are accessed by a tool in a hotbar slot. That has a huge range of different applications in MC for switching tools, food, etc. I am applying it to weapons in the suggestion. It can be more generalized.

How do you draw from a sub inventory? For the weapons thing you would create filters for the item ids I suppose.

GrimPack has pulled together so many code elements it is a huge resource of functionality.

The pokeball for instance is just amazing. I used it last night to capture a Thaumcraft Wisp in the Nether. If you have ever played this mod you will know that Wisps move very erratically and the hostile ones in the Nether snipe at you and often come in packs. With the pokeball I could keep aiming and spamming until it grabbed it. Nothing else like that although there are other entity capture tools.

You have a goldmine of code and limited time. I am willing to help. I compiled from source this morning and setup Eclipse. I am also familiar enough with Github operations, etc.

**Comment by grim3212** [comment]
@scottosx Could you send me a PM on Curse

**Comment by grim3212** [comment]
For right now I am closing this... Possibly will reopen later
