### ISSUE TITLE
[Suggestion] Add in Steel Multitools

### ISSUE THREAD

**Issue by grim3212** [grim3212/grim-pack#29]
One step to becoming more interconnected as requested https://minecraft.curseforge.com/projects/grim-pack?comment=10

Add in steel multi-tools and possibly other multi-tools for the other tool materials.

**Comment by drakray** [comment]
I suggest maybe make use of the BaseMetal and ModernMetal API, they add a lot of different ore already made to be used, maybe as a soft dependency

**Comment by grim3212** [comment]
Actually for now I was thinking of the other materials that are found in the Grim Pack so steel and black diamond.
