### ISSUE TITLE
[Suggestion] Iron Cage w/ mobs

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#32]
It might be nice to make the Iron Cage have 1 input slot, that accept Pokeball w/ mob inside.
The Cage should then render the mob, with a "random" movement to make it "move".
It could use the same scaling as Mob Spawner, but only be decorative

What do you think?

**Comment by grim3212** [comment]
Yeah I think it is a cool idea. Working on it now.

**Comment by grim3212** [comment]
bbf751c closes this. Should be up on curse soon.
