### ISSUE TITLE
[Bug] Weirdness with Blacklisting

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#37]
I made blacklist for all mineral resources, and the normal recipe don't show normally(might be a mod conflict, will try with only Grimpack), but Shift-Click work(1goldblock don;t show 9 ingot, but S-C give 9 ingot)
the weird thing is, if I use 8 to shape ChestPlate, I can grab 4(normal), but if I put the 9th ingot:

![2016-09-14 23_56_51-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/4303126/18537938/fbdbe1a8-7ad6-11e6-9da4-d43c289b1104.png)

**Comment by drakray** [comment]
Iron and Diamond same bug
Grimpack 30
Forge 2087

**Comment by drakray** [comment]
Bug exist with only Grimpack, Shift-Click won't as it's an InventoryTweak feature

**Comment by grim3212** [comment]
So the shift clicking I was unable to recreate but I did fix the issue above which may have fixed it.
This also includes a config option to return the default result if an item is blacklisted or not on the whitelist. This is on by default.
You can try it out here https://drive.google.com/file/d/0B9vcVyJ8SwHMazlkWmNfZFVPa3c/view?usp=sharing

**Comment by drakray** [comment]
All seems to work perfectly now :smile_cat:

**Comment by grim3212** [comment]
Awesome!
