### ISSUE TITLE
Feature Request: Glowstone Seeds

### ISSUE THREAD

**Issue by scottosx** [grim3212/grim-pack#40]
Thanks for your quick response to issues.

Req: Could you make it so that glowstone can grow on Netherack in the Overworld above level 15? Say around level 60 or below? This may play a prominent role is a modpack I am building.

Also, could it be possible to have a light emitting variation on the fungus?

The theme of my pack is a totally dark underground apocalyptic world with the player acting in a Promethus role as the light bringer. 

Much appreciated.

**Comment by grim3212** [comment]
So, for the glowstone you want it to actually generate when you create a world?

Also, I thought some Fungus already emitted light if not I should be able to do that.

**Comment by scottosx** [comment]
For my particular case I would not want the Glowstone in world gen, besides the regular mechanics in the Nether of course. Others may, so possibly a configuration option? I want the player to quest for the seeds and then plant them to pacify areas of the world.
Same thing with the fungus. The player would intentionally infect an area to light it up.
Of course that is a specific use in my pack and flexibility is always better.

**Comment by grim3212** [comment]
Oh okay so just have like a config option for the level that glowstone seeds can be planted on?

**Comment by scottosx** [comment]
Right. I see that it is set here: https://github.com/grim3212/Grim-Pack/blob/e60e1df7712888d84e49e6399734d07e33c6ff6a/src/main/java/com/grim3212/mc/pack/world/blocks/BlockGlowstoneSeed.java#L96

Just make that variable.

**Comment by grim3212** [comment]
Alright sounds good. It will be in the release tomorrow.

**Comment by scottosx** [comment]
Thanks.

On the fungus I am not seeing anything like setLightValue(x) or similar. There might not be light emitting fungus yet but don't hold me to that. Preferably there would be a way to craft fungus variations that emit light. Like mix them with glowstone dust or the glowstone seeds. 

Something like a light value of 10 - 12 would do what I want.

**Comment by grim3212** [comment]
Okay so I was looking at the Fungus and I found that they are being set with a light level.  https://github.com/grim3212/Grim-Pack/blob/1.10/src/main/java/com/grim3212/mc/pack/world/blocks/WorldBlocks.java#L38

So just wondering what you think?

**Comment by scottosx** [comment]
Ok, cool. That will work. Probably no need for further revision.

**Comment by grim3212** [comment]
Alright then closing this.
