### ISSUE TITLE
[Suggestion] Portable Workbench compatibility

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#41]
Would be nice if the PW could have the JEI + functionnality of recipe autofill
Other crafting table already have it so that's a plus :)

Thanks

**Comment by drakray** [comment]
Maybe also a portable version of X table?
everything configurable, as always :D

**Comment by grim3212** [comment]
So yeah for the portable workbench I could add JEI functinality.
Also for the X table I am not sure what you mean.

**Comment by drakray** [comment]
the multiplicative one, iron and diamond :P

**Comment by grim3212** [comment]
Oh, haha okay.
