### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Chunkimunki** [grim3212/grim-pack#42]
- Could the spikes make a sound when deployed.
- Captured mobs via pokeball  when put into cage emit a redstone signal - thinking of trophy quest in an             adventure map kinda thing.
- Item/block detectors....possible update of Triggers mod by Ratismal? He seems not to want to respond to any communication about continuing this Great mod.

**Comment by grim3212** [comment]
- I like the spikes idea
- You can get a redstone signal out using a comparator
- I don't know about updating a mod that is only in 1.8. I mainly have been updated mods that are from beta or early Minecraft days like 1.2.5

**Comment by grim3212** [comment]
Although if you have ideas for the type of item block detectors I might be able to add in my own.

**Comment by Chunkimunki** [comment]
For the item/block detectors I suppose you'll probably follow the theme already in the mod and go for line of sight versions- in the block you could have a slot to place  whatever you want to detect-possibly selectively registering items/blocks in hand/inventory/placed etc.

 However;as great as your detectors are;  for map making their use is a bit of a giveaway for player identifying as anything other than an opaque block stops the signal making the gap obvious where they are. A work around at the moment is to use the 'sneaky block' from Dark Utilities so you can disguise glass in front to blend in with a build.

 I much prefer the proximity method as per the Entity Detector block in the Random Things mod - very flexible- of course there's always the _cough_ code for the Triggers mod waiting for some love and attention - the ultimate as far I can perceive.

 Hope this waffle is of use - Cheers

**Comment by grim3212** [comment]
For hiding of the detectors you can use Colorizer blocks since they don't count as opaque or a full block.

**Comment by grim3212** [comment]
New secret feature in Industry that is basically the sensor I am working on. It's really basic right now but I plan on finishing it this weekend.

**Comment by grim3212** [comment]
The Specific Sensor should be what you want. Hopefully it works for you. 😄
