### ISSUE TITLE
Ticking Entity 1.8.9

### ISSUE THREAD

**Issue by scottosx** [grim3212/grim-pack#46]
When added grill. Biome null again or change not propagated to other Grim versions?

Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at com.grim3212.mc.decor.tile.TileEntityGrill.func_73660_a(TileEntityGrill.java:119)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at com.grim3212.mc.decor.tile.TileEntityGrill.func_73660_a(TileEntityGrill.java:119)

-- Block entity being ticked --
Details:
    Name: grill // com.grim3212.mc.decor.tile.TileEntityGrill
    Block type: ID #451 (tile.grill // com.grim3212.mc.decor.block.BlockGrill)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-150,83,-308), Chunk: (at 10,5,12 in -10,-20; contains blocks -160,0,-320 to -145,255,-305), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['ScottoMotto'/458, l='MpServer', x=-138.40, y=79.32, z=-171.38]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 8.00,64.00,8.00 - World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 5296684 game time, 5484732 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 48 total; [EntityDog[''/0, l='MpServer', x=-99.78, y=80.00, z=-270.53], EntityPlayerSP['ScottoMotto'/458, l='MpServer', x=-138.40, y=79.32, z=-171.38], EntityChicken['Chicken'/90758, l='MpServer', x=-178.31, y=81.00, z=-178.25], EntityZombie['Zombie'/637056, l='MpServer', x=-185.50, y=15.00, z=-173.50], EntityZombie['Zombie'/706307, l='MpServer', x=-177.50, y=22.00, z=-184.50], EntityZombie['Zombie'/706308, l='MpServer', x=-176.50, y=22.00, z=-184.50], EntityKiwi['Kiwi'/90768, l='MpServer', x=-159.94, y=75.00, z=-222.50], EntityBat['Bat'/706201, l='MpServer', x=-129.65, y=60.02, z=-110.38], EntityPlayerDummy['entity.rfpr.PlayerDummy.name'/95255, l='MpServer', x=-138.40, y=79.32, z=-171.38], EntityAuraNode['Aura Node'/573975, l='MpServer', x=-139.50, y=94.50, z=-292.50], EntitySpider['Spider'/706348, l='MpServer', x=-190.50, y=20.00, z=-148.50], EntityCreeper['Creeper'/682029, l='MpServer', x=-149.50, y=19.00, z=-170.50], EntityZombie['Zombie'/702909, l='MpServer', x=-80.31, y=28.25, z=-176.31], EntityBat['Bat'/641973, l='MpServer', x=-146.28, y=55.00, z=-149.25], EntityBat['Bat'/641974, l='MpServer', x=-150.71, y=55.87, z=-157.28], EntityDog[''/87749, l='MpServer', x=-111.22, y=80.00, z=-274.22], EntitySophisticatedWolf['Cisco'/87748, l='MpServer', x=-101.00, y=80.00, z=-272.69], EntitySkeleton['Skeleton'/637007, l='MpServer', x=-215.50, y=28.00, z=-169.50], EntityZombie['Zombie'/637006, l='MpServer', x=-215.31, y=28.00, z=-167.63], EntityBat['Bat'/706247, l='MpServer', x=-149.50, y=29.04, z=-173.28], EntitySpider['Spider'/645190, l='MpServer', x=-173.50, y=23.00, z=-159.50], EntityEnderman['Enderman'/637009, l='MpServer', x=-214.50, y=30.00, z=-172.50], EntityEnderman['Enderman'/637008, l='MpServer', x=-214.69, y=27.00, z=-164.66], EntitySkeleton['Skeleton'/637010, l='MpServer', x=-213.50, y=59.00, z=-161.50], EntityBat['Bat'/642281, l='MpServer', x=-213.63, y=29.84, z=-155.47], EntityPig['Pig'/667498, l='MpServer', x=-150.06, y=89.00, z=-96.41], EntityPig['Pig'/667496, l='MpServer', x=-150.44, y=85.00, z=-101.13], EntityPig['Pig'/667497, l='MpServer', x=-146.56, y=87.00, z=-97.13], EntityBat['Bat'/642282, l='MpServer', x=-214.44, y=28.97, z=-154.25], EntityPig['Pig'/667500, l='MpServer', x=-143.44, y=84.00, z=-99.06], EntityPig['Pig'/667494, l='MpServer', x=-153.91, y=87.00, z=-97.41], EntityPig['Pig'/667495, l='MpServer', x=-147.69, y=85.00, z=-100.47], EntitySheep['Sheep'/667492, l='MpServer', x=-152.19, y=79.00, z=-113.50], EntityBrainyZombie['Angry Zombie'/636774, l='MpServer', x=-123.50, y=62.00, z=-167.50], EntityPig['Pig'/667493, l='MpServer', x=-145.38, y=86.00, z=-96.91], EntityEnderman['Enderman'/637051, l='MpServer', x=-171.56, y=23.00, z=-159.78], EntityCow['Cow'/649595, l='MpServer', x=-188.22, y=82.00, z=-136.41], EntityPig['Pig'/90739, l='MpServer', x=-209.31, y=87.00, z=-184.53], EntityCreeper['Creeper'/706424, l='MpServer', x=-105.50, y=26.00, z=-140.50], EntityZombie['Zombie'/706297, l='MpServer', x=-72.50, y=35.00, z=-210.50], EntityBat['Bat'/637053, l='MpServer', x=-174.58, y=14.18, z=-181.48], EntityPig['Pig'/90741, l='MpServer', x=-211.56, y=85.00, z=-184.03], EntityPig['Pig'/90740, l='MpServer', x=-212.56, y=85.00, z=-182.78], EntitySkeleton['Skeleton'/637054, l='MpServer', x=-183.16, y=15.00, z=-173.28], EntitySheep['Sheep'/662899, l='MpServer', x=-168.41, y=80.00, z=-124.25], EntityCreeper['Creeper'/706422, l='MpServer', x=-103.50, y=26.00, z=-136.50], EntityCreeper['Creeper'/706423, l='MpServer', x=-104.50, y=26.00, z=-137.50], EntityCow['Cow'/665076, l='MpServer', x=-192.28, y=81.00, z=-125.06]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by scottosx** [comment]
Looking at the source I believe this error is referring to the property 'active' set in FireplaceBase https://github.com/grim3212/Grim-Pack/blob/1.10/src/main/java/com/grim3212/mc/pack/decor/block/BlockFireplaceBase.java

It is not being set or something. Trying to understand.

**Comment by grim3212** [comment]
Quite a bit things changed from the 1.8.9 version to 1.10. 
https://github.com/grim3212/Grim-Pack/blob/1.8/src/main/java/com/grim3212/mc/decor/tile/TileEntityGrill.java#L119

All it would really need is to check to make sure the the block is an instanceof blockgrill
