### ISSUE TITLE
Game does not respond type crash

### ISSUE THREAD

**Issue by Chunkimunki** [grim3212/grim-pack#47]
Is this anything to do with the mod and is it enough info?- the game just stops responding when you try and quit but does not exit with a crash report just spams the console with the following.

net.minecraft.world.World.markAndNotifyBlock(World.java:368) ~[aid.class:?]
[17:06:47] [Server thread/ERROR]: Index: 1 Listeners:
[17:06:47] [Server thread/ERROR]: 0: NORMAL
[17:06:47] [Server thread/ERROR]: 1: ASM: com.grim3212.mc.pack.util.event.BlockChangeEvents@3f90bc74 neighborNotifyEvent(Lnet/minecraftforge/event/world/BlockEvent$NeighborNotifyEvent;)V

using Forge 1.10.2-12.81.2085 with RTG mod(latest) / Reccurrent Complex / WTF Caves + others

Cheers

**Comment by grim3212** [comment]
What were you doing when this happened? It looks like a problem with it but I am not sure because I can't reproduce it.

**Comment by Chunkimunki** [comment]
The chunks stopped generating as I was flying around so tried to quit and relog back in - game froze and the console kept logging the above error. I suspect that it is a problem with the other worldgen mods particularly RTG and Recurrent Complex - these guys have been a pain with them needing to tweak their compatibility with other mods

**Comment by grim3212** [comment]
Most likely what happened was that it errored before you quit that's why the chunks stopped loading. I am pretty sure this is an issue on my end. Also, try the latest version I changed the affected file slightly. But, it might fix it.
