### ISSUE TITLE
I am having an issue where the workbench upgrades do not double/quadruple my output from crafting!

### ISSUE THREAD

**Issue by bluewizard24** [grim3212/grim-pack#48]

**Comment by grim3212** [comment]
Make sure that you have the config option enabled.

**Comment by grim3212** [comment]
I am closing this right now since I am pretty sure that they work. They are just disabled by default.

**Comment by scottosx** [comment]
The multiplying should be enabled by default. Otherwise, why would a person pay for the upgrade vs. the standard crafting table?  Sure. it looks nicer but...

**Comment by grim3212** [comment]
Well mainly it was disabled by default for easy setup on servers since these can end up becoming really overpowered.
