### ISSUE TITLE
More Config

### ISSUE THREAD

**Issue by MacGynan** [grim3212/grim-pack#49]
I'm trying to find a way to disable worldgen of gunpowder reeds so you have to craft it in a 9x9 crafting table. Also the ability to decide what recipes can be doubled/quadrupled in the crafting tables. having these config would be vary helpful.

**Comment by grim3212** [comment]
So for the worldgenconfig I thought that I already had it already configurable but I guess is missed a few I will work on that. Also, the crafting table config should already be in there.

**Comment by MacGynan** [comment]
Thanks. also what exactly does this mean? (B:"Workbench whitelist else blacklist"=false)

**Comment by grim3212** [comment]
Sorry it's poorly worded but if true then the list acts as a whitelist if false then a blacklist. It should also have a tooltip that goes into more detail.

**Comment by MacGynan** [comment]
Thanks.
