### ISSUE TITLE
Crash with partial door

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#5]
I got this crash when I right-click on the top part of a door, if the bottom part is not visible
http://pastebin.com/WRHG2haK

I can still click without crash when it is the top part that is missing.
I must destroy the bottom part to get the door, and replace it to make it complete again

If I destroy the top-only part, I don't get a door.
EDIT: I got the door when breaking top part.

**Comment by drakray** [comment]
If I play on my server, the client crash, but not the server

**Comment by grim3212** [comment]
How are you able to get half doors? Or I might be misunderstanding the problem.

**Comment by drakray** [comment]
The door just become half when I go far from its chunk and come back or quit and relog.
A door placed when facing North, with the hinge on the left, always stay the same, but a door placed when facing  south with hinges on the right completely disappear, but do not allow to pass through(I can still interact with thing behind)

**Comment by grim3212** [comment]
Okay I think this has to do with a problem in Minecraft Forge with disappearing doors. https://github.com/MinecraftForge/MinecraftForge/commit/f088e3df6b73c8e92f3a24cef5431ae783441acf

Maybe try updating and see if this fixes the partial doors and I'll also release an update to just make sure that it is a door hopefully to stop that problem if this ever occurs again.

**Comment by drakray** [comment]
This seems to have fix the problem nicely, thanks(I didn't have the latest version because in my last modpack it made a mod crash, which I seems to have removed :P )
