### ISSUE TITLE
[Weird] Treasure Mob front

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#50]
For some reason, the Treasure Mob face seems to be where the hinge is, instead of the open side of the chest shape.
Also, is it supposed to always be open?

**Comment by grim3212** [comment]
Yeah I noticed the face issue and was meaning to fix it. Also, it was always open in the original mod so I left it.

**Comment by drakray** [comment]
Might be nice to have it close, and for a right-click on it to make it aggressive >:D

**Comment by grim3212** [comment]
There might possibly be changes coming to Treasure Mobs! :) 
Also, 22fd8b1d8d5d5162d98e857979c97722f5731c37 fixes the facing issue
