### ISSUE TITLE
Destruction Wand breaks GrimPack Ores

### ISSUE THREAD

**Issue by scottosx** [grim3212/grim-pack#52]
Have trie to add them in the spared list in the config but still nada. Format grimpack:black_diamond_ore and black_diamond_ore

**Comment by grim3212** [comment]
So, this would work with a restart. But, I just changed it so that removing and adding shouldn't require a restart.

**Comment by scottosx** [comment]
What is the correct listing format? Prefixed with grimpack:

**Comment by grim3212** [comment]
Yeah I forgot to add the grim pack ores to it by default.
