### ISSUE TITLE
Obsidian Milk Bucket Not Milking

### ISSUE THREAD

**Issue by scottosx** [grim3212/grim-pack#53]
Not cows, pigs, or sheep by the normal means of right click or any other.

**Comment by grim3212** [comment]
Umm, are you possibly in creative because it only does it in Survival.

**Comment by scottosx** [comment]
No, in survival 1.10.2. Works for water. Haven't tried lava yet. The stone bucket did milk. Haven't tried the gold yet.

**Comment by grim3212** [comment]
I have no idea why it is not working then. I just tested it on my version and it worked. Are you running anything special.

**Comment by scottosx** [comment]
Nope. This is a test survival game using only GrimPack, JEI, JER, Waila, JourneyMap, Fast Leaf Decay, SuperMiner and Packing Tape. I'll try again. The bucket was made with an iron workbench where you get 2 for 1, if that matters.

**Comment by scottosx** [comment]
Nope. I just tried on a cow and a sheep. Right clicking no milk. I can beat them to death with it though :)

**Comment by grim3212** [comment]
What happens without the other mods. It might be a conflict with the others.

**Comment by scottosx** [comment]
I suspected that if anything if would be SuperMiner as that is the most wide ranging. Still no milk without it. Will try and selectively disable others. What version of Forge are you using? I am using  12.18.1.2094. This is a Curse modpack custom profile.

**Comment by grim3212** [comment]
It uses 2076

**Comment by scottosx** [comment]
I switched to that and still no milk. I will disable the others.

**Comment by scottosx** [comment]
Ok. So I disabled all addons. Did nothing. But..... I decided to make a new bucket with a regular crafting table and see if that mattered. It worked. I milked a cow and sheep. Was able to fill the whole bucket. Did you try with the iron workbench on your end? Stacking unstackable items seems kind of fishy.

**Comment by grim3212** [comment]
Wow. I guess it could cause some problems. That would be an easy check to stop from crafting unattackable items. But that would stop a lot of recipe's.

**Comment by scottosx** [comment]
That would probably be too much of a heavy hand fix. For instance, tools like pickaxes and such work fine although they are unstackable. I will continue to test and make sure that is truly the issue.      It could only affect this one item or there might be other variables in play.

**Comment by grim3212** [comment]
Well it is probably because NBT values get added on crafting.

**Comment by scottosx** [comment]
I will check it out with NBTEdit. The obsidian bucket is nice. I like the better buckets. I wonder why they display in units of 1000? Why not just units of 1. That translates to normal buckets right?

**Comment by grim3212** [comment]
They display in millibuckets and that is the default amount for one bucket in forge.

**Comment by scottosx** [comment]
That makes sense. I recall now seeing mB as the metric for many fluids.

**Comment by grim3212** [comment]
Okay, so I just tested this out on my end with both diamond and iron workbench. Every bucket was able to milk as well as pickup fluids.

**Comment by scottosx** [comment]
Odd. I definitely wasn't hallucinating :) Maybe just a quirk. I'll try to reproduce.

**Comment by grim3212** [comment]
Possibly Forge version? I just updated today.

**Comment by scottosx** [comment]
Possible. The bucket was created in the newest version and the one that worked was created in 2076.

**Comment by grim3212** [comment]
So, should I close this? Was this resolved?
