### ISSUE TITLE
Crossmod issue with Refined Storage

### ISSUE THREAD

**Issue by psychofad** [grim3212/grim-pack#56]
There apparently is some kind of issue with the way you use the ore dictionary that is causing recipe issues in Refined Storage mod,  wasn't sure if you were aware or even know what they are talking about.

See the issue here:
https://github.com/raoulvdberge/refinedstorage/issues/428

can you shed any light on this?

**Comment by grim3212** [comment]
No, I did not even know about this. I'll look into why this is happening.
