### ISSUE TITLE
[CTD] After updating to recommended Forge 2097

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#58]
http://pastebin.com/UpJ2eVSU
no crash on Forge 2095

**Comment by grim3212** [comment]
Could you try with Forge 2099. I think that there were some problems in that build. I just tested it on 2099 and am not getting any error.

**Comment by drakray** [comment]
Work again, seems like the thing they did on 2096 did "[Broke some existing setups](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2099/forge-1.10.2-12.18.2.2099-changelog.txt)"
Anyway it work now, so not a ctd anymore :)
