### ISSUE TITLE
[Suggestion] Change in recipe/way of doing

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#6]
I think a good way of doing all the furniture thing would be like the Bibliocraft framed block, or the MrCrayfish one: a single block with a single recipe, that can be clicked on with another to apply texture. this would remove the need for oh so many recipe in JEI, some [visual glitch in recipe](http://imgur.com/xOvKH1C) (the glitch is only visual in JEI, the block have the correct texture on creation), and maybe allow for more variation, like all of Chisel variation.

**Comment by grim3212** [comment]
Yeah I was thinking the same way recently. Especially because certain blocks can end up costing a ton of expensive resources just for the looks.

**Comment by grim3212** [comment]
The latest push c17bd56 added what you requested. Needs some testing so if you would like to try it and give me some feedback that would be awesome. 

You can get it here https://minecraft.curseforge.com/projects/grim-pack/files/2320759

**Comment by drakray** [comment]
I'll try it both on my server and in SSP

**Comment by drakray** [comment]
Seems to work very well, no crash yet.
Some block behave weirdly, must be cause by weird custom mod rendering.
Some block do not work, like leaves, glowstone and most tile entity(furnace, etc)

Colorizer block, Grill, Fence and Gate are not texturable.
Shift-clic to reset texture do not work with Fireplace, Stove, Firepit, firering not Chimney.(a tool, like a brush of sort, could be use to circumvent the problem maybe?)

Breaking Grill with hand in Creative made the Server Crash
http://pastebin.com/wywKsuN0

**Comment by drakray** [comment]
Resatarted client and server, grill is gone

**Comment by grim3212** [comment]
Okay so I just pushed some new changes which completely changes it again.  This probably won't crash worlds that already have the blocks but they won't be textured properly. Added a brush to remove blocks stored and also see information with a shift right click. Everything above should hopefully be fixed from what I tested. 

Also, tile entity's and a few other blocks are blacklisted to prevent issues.
What do you think of the current texture? I made it really quick as a placeholder so I was wondering what do you think it should look like? 
Finally recipes. Any thoughts on what they current;y are. I think I might tone down how many colored blocks you get.

You can try it out https://minecraft.curseforge.com/projects/grim-pack/files/2320906

**Comment by drakray** [comment]
No crash yet! :D ;)
In Creative, source texture is not consumed, but is still gotten back when creative breaking.
Textured Lamp Post do not drop texture block when broken with a pickaxe.

**Comment by drakray** [comment]
The placeholder animated texture is nice I think, could even be used as-is :D
I think using Netherrack for the fiery block would be better, as they are light source which doesn't extinguish by themselves.

Maybe tone down the number of Colorizer block gotten by craft, but give more Chimney block, as 6 Colorizer for 1 Chimney is rather expensive(maybe 6/3?)

**Comment by grim3212** [comment]
I'll try and fix the issues later tonight. And yeah I might change the texture slightly but I also kinda like it now.

Also what do you mean by fiery block?

**Comment by drakray** [comment]
No problem, take your time, there's nothing really game breaking or urgent, just a little annoyance if you don't know about it.

Firepit, Fireplace, Firering and Stove, Maybe Grill also, Coal is too easy I think.
Sure, Netherrack is pretty mush the most common block available, but is still a little hassle to get, and the Cannon eternal fire source :P

**Comment by grim3212** [comment]
Alright hopefully the last beta before a release of all the changes.
Should include all the fixes above as well as issues #10, #9, #8 

https://minecraft.curseforge.com/projects/grim-pack/files/2321004

**Comment by drakray** [comment]
Small bug: make 2 Grills, place one, texture it, destroy it, now you have 2 unstackables grills in inventory. Replacing them in the world without texturing and destroying them will make them stack again.
Uranium seems to work fine, radiation is back(was not working before)

Typo in the Instruction manual, page about Dairy, Butter Churn says it give Cheese.

---

These bellow are mostly opinion

Iron Stick should be named Iron Rod(to fit other mod's rod), and have oreDict name "rod", to be used in Metal Rod recipe.
Metal Rod should have rodMetal, stickMetal and rod instead of iron, and be used in more recipe, namely Iron Chain and Iron Cage to prevent conflict with, for exemple, MCA's Ring(and many more Iron Ring).

Maybe also give out 2 instead of 1, since Metal Rod can be use to make Metal Rod lol.

Chisel and Hammer might also conflict(could use rodMetal to fix), same with Iron Spike and Part(almost all recipe that use only Iron should be avoid I think, to many mods use that, but that's just my opinion).

Soda should maybe have tooltip, CO2 seems a little expensive.

**Comment by grim3212** [comment]
So, I think I changed everything but one last thing before I put out a release. What do you mean that Soda should have a tooltip? What should it say?

**Comment by drakray** [comment]
Something to say what it does, without having to look in the Manual.
Completely optional though, will just make people look more into it.(I didn't think to look into it at first)

Also, I don't know why, but sometime, very rarely, when me or my roommate log on the server, we get another manual, even though we already got it(I made a custom recipe to turn it back into a Vanilla Book, always useful)

**Comment by grim3212** [comment]
Alright I think I got everything done. Just added a release file to curseforge.
You can get it here and I guess I will close this issue.
https://minecraft.curseforge.com/projects/grim-pack/files/2321109
