### ISSUE TITLE
Metal Rod

### ISSUE THREAD

**Issue by scottosx** [grim3212/grim-pack#63]
The Metal Rod for Iron Spikes shares a recipe with rods from other mods. Specifically the Iron Rod from Immersive Engineering. When this mod is present you cannot make the iron spikes.

I suggest that the recipe for Iron Spikes also can accept iron and steel rods besides the generic metal rod.

**Comment by grim3212** [comment]
Yeah, I may end up changing the recipe or something instead of changing OreDictionary stuff.

**Comment by scottosx** [comment]
First pull request (now merged) closes this.

**Comment by grim3212** [comment]
Alright
