### ISSUE TITLE
[Suggestion] Centred Post

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#64]
To go with the Sloped Post, a simple Centred Post, same functionality as Sloped.
Maybe also add more placement option if possible, like sideways(now there are 2, floor and ceiling, wall could be nice)

Keep up the good work! :D

**Comment by grim3212** [comment]
So I am not quite sure what you mean. What would a centered post look like.
Also, the sideways placement would be a nice addition.

**Comment by drakray** [comment]
something the shape of Wall, 8 pixel wide, centered on block, without side connection
![2016-12-16_13 09 06](https://cloud.githubusercontent.com/assets/4303126/21273338/15d2bfca-c391-11e6-9cb1-1584069071c2.png)
Be able to do that, but with your colorable block

**Comment by grim3212** [comment]
Oh okay that makes sense. Did you want this to work like the wall where it connects to others?

**Comment by drakray** [comment]
That could be nice, maybe with a config to turn on/off, or 2 different block could be nice, one that connect and not the other(with recipe to cycle from one to the other)(preferred option)

**Comment by drakray** [comment]
also, make the pillar 6 way too please
