### ISSUE TITLE
[Issue] Corruption can't be disabled

### ISSUE THREAD

**Issue by accessdenied0** [grim3212/grim-pack#7]
Hey @grim3212, 

I like your work with these mods and your effort to keep them alive. Sadly I have to submit this work to you: I can't disable the Corruption in my world. I disabled it before I started my world and it still got generated in the Nether.

In addition in your manual is the page "Extended Worldgen" broken in my case. (broken texture, no buttons). It didn't crash but my console put this code out: http://pastebin.com/D8YRgJya

Maybe you can have a look into this,

access_denied

**Comment by grim3212** [comment]
So that config option only disables the spread of corruption. Just added an option to disable the generation.

**Comment by accessdenied0** [comment]
Thank you.
