### ISSUE TITLE
[CTD] UnsupportedOperationException after mod update

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#73]
I updated Aroma1997Core to 1.1.1.1 from 1.1.1.0, and GrimPack crashed minecraft onload :/
Any idea why? there is no reference to other mods in the log

http://pastebin.com/rLKxCdA1

using Grim Pack-1.10.2-3.4.17.52 for 1.10.2, Forge 2185

**Comment by grim3212** [comment]
Hmm, I guess it doesn't like how I add entity spawns. I don't know why this would happen as it has worked before. I will try to figure out a fix.

**Comment by grim3212** [comment]
I just did a test with the same version of Aroma and Forge but was unable to reproduce the crash. I think it may be another mod causing the issue with adding spawns.

**Comment by drakray** [comment]
it must be in interaction with either AromaCore or AromeDimension, as the crash went aways after I rolled back to Core 1.1.1.0 and Dimension 1.2.0.2, from 1.1.1.1 and 1.2.0.4 respectively(sorry, I forgot to mention AromaDimension)

**Comment by grim3212** [comment]
Did you do anything special that caused this to happen. I just added AromaDimension and still no crash.

**Comment by drakray** [comment]
nop, I had .0 and .2 working, tried to update to .1 and .4, and got a crash from grimpack before I could do anything.
Maybe it's an exotic mod interaction in my 100+ mod list

EDIT: I just tried again to be sure it was not a 1 time thing, but I still crashed at Forge Loading 4/7
EDIT2: [Link](https://www.dropbox.com/s/xsgpa3umiijvzvl/TEST.zip?dl=0) to my crashing instance

**Comment by grim3212** [comment]
Well got it to crash with that trying to figure it out now.

**Comment by grim3212** [comment]
Figure it out

917d862 closes this

**Comment by drakray** [comment]
seems to work well, thanks :D
