### ISSUE TITLE
crash when making coal block with grim-industry and ye old tanks

### ISSUE THREAD

**Issue by kzintiwife** [grim3212/grim-pack#77]
Took me a while but i found the 2 mods that were causing this really strange crash. when making coal blocks in a crafting table - the game was crashing.  the shadowmc didnt cause it by itself with grim.  once i turned grim industry off, the crashes stopped. 

 Here is the report. 
[crash-2017-02-16_05.01.26-client.txt](https://github.com/grim3212/grim-pack/files/779992/crash-2017-02-16_05.01.26-client.txt)

**Comment by grim3212** [comment]
So, I have been doing some testing and I still am uncertain why this is happening. I have a feeling that it has do with the way YeOldeTanks is handling it's recipes. The same error occurred with RandomThings a while ago. https://gist.github.com/4rz0/0e35181ca73e32b97d5f787896291ef8

I removed all the recipes and got it working with Industry so I guess somewhere it is conflicting with some recipe.

**Comment by grim3212** [comment]
Should be fixed with YeOldeTanks https://github.com/shadowfacts/YeOldeTanks/commit/3d27fcd7e8e8b6b6819364b221483781bf23c466

If not let me know.
