### ISSUE TITLE
FREQ: Ore Dictionary additions to add "lazy" cross-mod compatibility with Harvestcraft

### ISSUE THREAD

**Issue by Syndaryl** [grim3212/grim-pack#80]
I use the following oreDict entries added via my MineTweaker/CraftTweaker scripts to add cross-mod compatibility with Harvestcraft.

```
<ore:bread>.add(<grimpack:bread_slice>);
<ore:foodCheese>.add(<grimpack:cheese>);
<ore:foodDough>.add(<grimpack:dough>);
<ore:foodScrambledegg>.add(<grimpack:eggs_cooked>);
<ore:listAllbread>.add(<grimpack:bread_slice>);
<ore:listAllbutter>.add(<grimpack:butter>);
<ore:toolCuttingboard>.add(<grimpack:knife>);
<ore:toolJuicer>.add(<grimpack:mixer>);
```

This allows Harvestcraft recipes to use Grimpack tools and base ingredients. Not sure if you want to use Pam's ingredients in your recipes, but I don't see what would be disturbed by allowing use of Pams cooking tools (Knife, mixer) in yours.

Not for Harvestcraft, but for other mods, adding the Oil Ore to the oredict (and using it in your machines) will also help with cross-mod compatibility:

```
<ore:oreOil>.add(<grimpack:oil_ore>);
```

**Comment by grim3212** [comment]
Oil ore was already registered. Maybe it wasn't in the beta release.
