### ISSUE TITLE
Biomes O Plenty plants won't plant in Clay Pot

### ISSUE THREAD

**Issue by Syndaryl** [grim3212/grim-pack#82]
... which makes me sad, because there's so many BOP plants to decorate with. Plants from e.g. Random Things, or Harvestcraft crops, work correctly, so this seems to be specifically a problem with BOP.

**Comment by grim3212** [comment]
This seems to be on BOP's end. I make sure to allow all plants the option of being able to be placed on the pot but they have to make sure they check with canSustainPlant. I don't really have any easy way of making this possible.

**Comment by grim3212** [comment]
Fixed by Biomes O Plenty
