### ISSUE TITLE
Lumberaxe Compatibility

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#85]
Please take a look at https://github.com/DoubleDoorDevelopment/Lumberjack/issues/17

**Comment by drakray** [comment]
Removing the multi material fixed lot of bug, but I think you are not setting steel ingot as a repair material on it's own?

**Comment by grim3212** [comment]
Really? Is it only not working as a multitool? Because https://github.com/grim3212/grim-pack/blob/master/src/main/java/com/grim3212/mc/pack/industry/item/IndustryItems.java#L208 you can see that it is being set for the tool material.

**Comment by drakray** [comment]
i'm deep in debugging now, to find why I got weirdness with Lumberjack and Steel as a whole

**Comment by drakray** [comment]
using d3core materials.json to set steel won't work because yours is registered, which seems right, but LJ don't make a recipe for it :/

**Comment by drakray** [comment]
so, all you steel stuff seems to work as intended, multitool exist and don't bug/crash
something must not be right on LJ side, maybe because of FunOres, will check with them

**Comment by grim3212** [comment]
Alright tell me if you find anything
