### ISSUE TITLE
Bauble Compatibility

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#86]
I just tested, and the Grave do not capture Bauble's Inventory

Also, it doesn't respect gamerule keepInventory true("standard" inventory goes in Grave, Bauble stay in hand as per gamerule)

**Comment by drakray** [comment]
I suppose you didn't forgot to put an additional row on the grave for the 7 Bauble slot? :)
Inventory get bigger quickly with mods lol XD

**Comment by grim3212** [comment]
Lol yep I made sure it fits!
