### ISSUE TITLE
[ModCompat] WailaHarvestability Error Output

### ISSUE THREAD

**Issue by drakray** [grim3212/grim-pack#90]
https://pastebin.com/iSRcrpwb

**Comment by grim3212** [comment]
Interesting, I'll look into it

**Comment by grim3212** [comment]
Is this still a problem?

**Comment by drakray** [comment]
I dont think so, been a while since i had this, will keep looking and post if i see it again, but you could probably mark as solved until further notice

**Comment by grim3212** [comment]
Okay thanks for the update! Tell me if ever happens again.
