### ISSUE TITLE
crash with Sling (1.11.2)

### ISSUE THREAD

**Issue by cursinorock** [grim3212/grim-pack#93]
Crash when i use Sling
Last version of forge for 1.11.2 (1.11.2-forge1.11.2-13.20.1.2425)
[crash-2017-07-27_20.32.13-client.txt](https://github.com/grim3212/grim-pack/files/1181559/crash-2017-07-27_20.32.13-client.txt)

Grim Pack-1.11.2-4.0.1.19

**Comment by grim3212** [comment]
Were you doing anything special to make this happen? I am having problems recreating the crash.

**Comment by cursinorock** [comment]
Just  shooting at a spider, happened after the ammunition had run out
