### ISSUE TITLE
Crash when break Cheese maker (1.11.2)(Grim Pack-1.11.2-4.0.1.20)

### ISSUE THREAD

**Issue by BuckTheWeasel** [grim3212/grim-pack#95]
Crash when break Cheese maker on Creative
 (i put the milk in and break the cheesmaker and it will crash)
https://pastebin.com/iG4BMJ9S

**Comment by grim3212** [comment]
I'm having problems reproducing this. Does this happen to you even without FoamFix or are you doing anything special to make this happen besides just putting milk in and breaking it?

**Comment by grim3212** [comment]
Closing this because I am unable to reproduce and no other information was given. Tell me if anyone is still experiencing this.
