### ISSUE TITLE
New Configuration Options

### ISSUE THREAD

**Issue by grim3212** [grim3212/grim-pack#96]
In the latest commit 9aca279 I added support for subparts of Cuisine to be disabled and enabled. This has been one of the most requested features and I am just wanted some feedback good or bad.

When you disable a subpart it will remove the block/item, any recipes crafting/smelting, remove manual pages or whole chapters. It will basically try to make anything to do with that part completely gone. 

##### Cuisine Config
```
cuisine {

    parts {
        B:"Enable SubPart chocolate"=false
        B:"Enable SubPart dairy"=true
        B:"Enable SubPart dragon fruit"=true
        B:"Enable SubPart health"=true
        B:"Enable SubPart pie"=true
        B:"Enable SubPart soda"=true
    }

    general {
        B:"Generate Cocoa Trees"=true
    }

}
```

Although sometimes an item like the 'knife' is used with recipes in the dairy subpart and the pie subpart so it will only be removed when both parts are disabled.

##### Conditions for Knife
```
"conditions": [
    {
      "type": "grimpack:part_enabled",
      "part": "cuisine"
    },
    {
      "type": "forge:or",
      "values": [
      	{
      		"type": "grimpack:cuisine_subpart_enabled",
      		"subpart": "dairy"
      	},
      	{
      		"type": "grimpack:cuisine_subpart_enabled",
      		"subpart": "pie"
      	}
      ]
    }
  ]
```

So, how an item/block/entity/whatever will be disabled depends on what else can or relies on it. This could end up being annoying for me but good for you.

The biggest pain is that I will need to modify all recipe jsons I just created which right now do not even support disabling of the parts themselves.

Any thoughts?

**Comment by drakray** [comment]
I think in the long run it would pay off, custom-wise.
While we are at it, maybe add config for tool durability, where 0 is indestructible? (you know i'm all about config lol)

**Comment by morsmage** [comment]
This would be fantastic, but I would take anything that lets me pick and choose the parts I want to use. I personally almost exclusively use the colorizer blocks and subsequent slopes, but in a couple of packs, I use a few other features (fans, extruder, etc.).

What does the "Enable _section_ part" part of the core config do right now? All I can see is that it takes the entries out of the book and the blocks _seem_ to be gone from world gen. Everything is still in craftable and present in JEI however.

I know that in the past, you used separate mods, but I imagine that is harder to maintain. Is that why you moved to the "pack" version?

**Comment by grim3212** [comment]
@drakray I will look into the tool durability config once I get this the way I like it. Configuration is good for everyone.

@morsmage Yeah, I think it will be nice for everyone to be able to disable parts since right now the pack covers such a wide variety of things. Also, in it's current state the enable section is broken. In the latest push it is fixed and will be back in working order when I finish the configurable subparts. What it is supposed to do is remove everything to do with the part including recipes, the block/item/registry stuff too. 
That is why I combined to one pack. It just makes my life a lot easier.

**Comment by morsmage** [comment]
Gotcha. Thanks for the hard work!

**Comment by JasonKillsUs** [comment]
hi Grim,
I wonder how to disable the coal to coal dust recipe, since it will disable the "tiny coal" from "actual addition" mod.

**Comment by grim3212** [comment]
@JasonKillsUs If you are in 1.12 just add the forge:false condition

**Comment by drakray** [comment]
is it for 1.11.2 too?

**Comment by grim3212** [comment]
No sorry it would be a huge backport that I just don't have time for.
